spring.application.name=TaskSphere
server.port=8082


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sisencodig-taskTracker
spring.datasource.username=postgres
spring.datasource.password=dgblood

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


